<?php
declare(strict_types=1);
require __DIR__ . '/../../includes/auth.php';
requireLogin();
require __DIR__ . '/../../includes/db.php';

$userId = (int) $_SESSION['user_id'];

$habitOptStmt = mysqli_prepare($conn, 'SELECT HABIT.habit_id, HABIT.habit_name
    FROM HABIT
    INNER JOIN CATEGORY ON HABIT.category_id = CATEGORY.category_id
    WHERE CATEGORY.user_id = ?
    ORDER BY HABIT.habit_name');
mysqli_stmt_bind_param($habitOptStmt, 'i', $userId);
mysqli_stmt_execute($habitOptStmt);
$habitOptResult = mysqli_stmt_get_result($habitOptStmt);
$habitOptions = mysqli_fetch_all($habitOptResult, MYSQLI_ASSOC);
mysqli_stmt_close($habitOptStmt);

$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    if ($action === 'add_milestone') {
        $milestoneHabitId = $_POST['habit_id'] ?? '';
        $label = trim($_POST['label'] ?? '');
        $eventDate = $_POST['event_date'] ?? '';

        $ownsHabit = false;
        foreach ($habitOptions as $opt) {
            if ((string) $opt['habit_id'] === (string) $milestoneHabitId) {
                $ownsHabit = true;
                break;
            }
        }
        if (!$ownsHabit) {
            $errors[] = 'Please select a valid habit.';
        }

        if ($label === '') {
            $errors[] = 'Please enter a label for this milestone.';
        }

        $dateObj = DateTime::createFromFormat('Y-m-d', $eventDate);
        if (!$dateObj || $dateObj->format('Y-m-d') !== $eventDate) {
            $errors[] = 'Please enter a valid date.';
        }

        if (empty($errors)) {
            $milestoneHabitId = (int) $milestoneHabitId;

            $stmt = mysqli_prepare($conn, "INSERT INTO CALENDAR_EVENT (user_id, habit_id, label, event_date, event_type) VALUES (?, ?, ?, ?, 'milestone')");
            mysqli_stmt_bind_param($stmt, 'iiss', $userId, $milestoneHabitId, $label, $eventDate);
            mysqli_stmt_execute($stmt);
            mysqli_stmt_close($stmt);

            header('Location: calendar.php?success=add');
            exit;
        }
    }

    if ($action === 'delete_milestone') {
        $eventId = $_POST['event_id'] ?? '';

        if (filter_var($eventId, FILTER_VALIDATE_INT) !== false) {
            $eventId = (int) $eventId;

            $stmt = mysqli_prepare($conn, "DELETE FROM CALENDAR_EVENT WHERE event_id = ? AND user_id = ? AND event_type = 'milestone'");
            mysqli_stmt_bind_param($stmt, 'ii', $eventId, $userId);
            mysqli_stmt_execute($stmt);
            mysqli_stmt_close($stmt);

            header('Location: calendar.php?success=delete');
            exit;
        }
    }
}

// DataTables handles pagination client-side now, so this just fetches
// everything (capped for safety) instead of slicing a page in PHP.
$eventStmt = mysqli_prepare($conn, 'SELECT CALENDAR_EVENT.*,
    SUBTASK.subtask_name,
    COALESCE(HABIT_VIA_SUBTASK.habit_name, HABIT_DIRECT.habit_name) AS habit_name
    FROM CALENDAR_EVENT
    LEFT JOIN SUBTASK ON CALENDAR_EVENT.subtask_id = SUBTASK.subtask_id
    LEFT JOIN HABIT AS HABIT_VIA_SUBTASK ON SUBTASK.habit_id = HABIT_VIA_SUBTASK.habit_id
    LEFT JOIN HABIT AS HABIT_DIRECT ON CALENDAR_EVENT.habit_id = HABIT_DIRECT.habit_id
    WHERE CALENDAR_EVENT.user_id = ?
    ORDER BY CALENDAR_EVENT.event_date DESC, CALENDAR_EVENT.event_id DESC
    LIMIT 2000');
mysqli_stmt_bind_param($eventStmt, 'i', $userId);
mysqli_stmt_execute($eventStmt);
$eventResult = mysqli_stmt_get_result($eventStmt);
$allEvents = mysqli_fetch_all($eventResult, MYSQLI_ASSOC);
mysqli_stmt_close($eventStmt);

$eventsForJs = array_map(function ($e) {
    return [
        'date' => $e['event_date'],
        'label' => $e['label'],
        'habit' => $e['habit_name'],
        'type' => $e['event_type'],
    ];
}, $allEvents);
?>
<!DOCTYPE html>
<html>
<head>
  <title>Calendar — Habit Track</title>
  <link rel="stylesheet" href="/assets/css/style.css">
  <link rel="stylesheet" href="Calendar.css?v=20260801-3">
</head>
<body>
<script>window.SERVER_ERRORS = <?php echo json_encode($errors, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>;</script>
  <div class="app-layout">
    <div class="sidebar">
      <?php require __DIR__ . '/../../includes/logo.php'; ?>
      <a href="../dashboard/dashboard.php" class="nav-item">Dashboard</a>
      <a href="../habits/habits.php" class="nav-item">Habits</a>
      <a href="../categories/categories.php" class="nav-item">Categories</a>
      <a href="../reminders/reminders.php" class="nav-item">Reminders</a>
      <a href="calendar.php" class="nav-item active">Calendar</a>
      <a href="../settings/settings.php" class="nav-item">Settings</a>
      <div class="sidebar-footer">
        <a href="../auth/logout.php" class="nav-item">Logout</a>
      </div>
    </div>
    <div class="main-content">
      <div class="page-header"><h1>Calendar</h1></div>
      <p class="calendar-subtitle">Most entries here are auto-generated by logging a subtask. You can also add your own milestones below to mark progress manually.</p>

      <div class="calendar-widget">
        <div class="calendar-header">
          <button type="button" id="cal-prev" class="btn-cal-nav" aria-label="Previous month">‹</button>
          <h2 id="cal-month-label"></h2>
          <button type="button" id="cal-next" class="btn-cal-nav" aria-label="Next month">›</button>
        </div>
        <div class="calendar-grid" id="cal-grid"></div>
        <div class="calendar-day-detail" id="cal-day-detail">
          <p class="cal-detail-empty">Click a day to see what happened.</p>
        </div>
      </div>

      <div class="settings-section">
        <h2 class="section-heading">Add a Milestone</h2>
        <div class="auth-card">
          <form method="POST" action="calendar.php">
            <input type="hidden" name="action" value="add_milestone">
            <div class="field">
              <select name="habit_id" class="select-input" required>
                <option value="">Select habit</option>
                <?php foreach ($habitOptions as $opt): ?>
                  <option value="<?php echo $opt['habit_id']; ?>"><?php echo htmlspecialchars($opt['habit_name']); ?></option>
                <?php endforeach; ?>
              </select>
            </div>
            <div class="field">
              <input type="text" name="label" placeholder="Milestone (e.g. Hit 30-day streak)" required>
            </div>
            <div class="field">
              <input type="date" name="event_date" required>
            </div>
            <button type="submit" class="btn-primary">Add Milestone</button>
          </form>
        </div>
      </div>

      <?php if (empty($allEvents)): ?>
        <div class="empty-state calendar-empty-below"><p>No activity yet. Log a subtask on the Subtasks page and it'll show up here automatically.</p></div>
      <?php else: ?>
        <h2 class="section-heading">Full activity log</h2>
        <table id="calendar-table" class="data-table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Habit</th>
              <th>Event</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($allEvents as $e): ?>
              <tr>
                <td><?php echo htmlspecialchars($e['event_date']); ?></td>
                <td><?php echo htmlspecialchars($e['habit_name']); ?></td>
                <td>
                  <?php echo htmlspecialchars($e['label']); ?>
                  <?php if ($e['event_type'] === 'milestone'): ?>
                    <span class="badge-milestone">Milestone</span>
                  <?php endif; ?>
                </td>
                <td class="actions-cell">
                  <?php if ($e['event_type'] === 'milestone'): ?>
                    <form method="POST" action="calendar.php">
                      <input type="hidden" name="action" value="delete_milestone">
                      <input type="hidden" name="event_id" value="<?php echo $e['event_id']; ?>">
                      <button type="button" class="btn-delete" data-confirm-message="Delete this milestone? This cannot be undone.">Delete</button>
                    </form>
                  <?php else: ?>
                    —
                  <?php endif; ?>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      <?php endif; ?>
    </div>
  </div>

  <script>
    window.CALENDAR_EVENTS = <?php echo json_encode($eventsForJs, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>;
  </script>
  <script src="Calendar.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="/assets/js/confirm-delete.js"></script>
  <script src="/assets/js/toast.js"></script>
</body>
</html>